---
title: "Danceability of Beyonce in Spodify"
subtitle: ""
author: 
  - Mehrnoush Mohammadi
thanks: "Code and data are available at: https://github.com/mehrnoush68/Spodify.git"
date: today
date-format: long
format: pdf
number-sections: true
bibliography: references.bib
---

```{r}
#| include: false
#| warning: false
#| message: false

#install.packages(c('rmarkdown', 'babynames', 'gh','here','httr','janitor','jsonlite', 'knitr','lubridate','pdftools','purrr','rvest','spotifyr', 'tesseract', 'tidyverse','usethis', 'xml2' ))

##install.packages("tinytex")

library(tinytex)
library(rmarkdown)
library(babynames)
library(gh)
library(here)
library(httr)
library(janitor)
library(jsonlite)
library(knitr)
library(lubridate)
library(pdftools)
library(purrr)
library(rvest)
library(spotifyr)
library(tesseract)
library(tidyverse)
library(usethis)
library(xml2)

```


# Introduction


# Data

@fig-beyond

```{r}
#| echo: false

beyonce <- 
  readRDS(here::here("data/raw_data/beyonce.rds"))
```

```{r}
#| label: fig-beyond
#| fig-cap: Danceability of Beyonce albums over time
#| echo: false

beyonce <- as_tibble(beyonce)

beyonce |>
  filter(album_release_date_precision == "day") |> 
  mutate(album_release_date = ymd(album_release_date)) |> 
  ggplot(aes(
    x = album_release_date,
    y = danceability,
    group = album_release_date
  )) +
  geom_point(alpha = 0.5) +
  theme_minimal() +
  labs(x = "Album release date",
       y = "Danceability")
```


@tbl-danceability

```{r}
#| label: tbl-danceability
#| tbl-cap: Average danceability of each Beyonce album
#| echo: false

beyonce <- as_tibble(beyonce)

beyonce |>
  filter(album_release_date_precision == "day") |> 
  mutate(album_release_date = ymd(album_release_date)) |>
  summarize(ave_danceability = mean(danceability), .by = "album_name") |> 
  knitr::kable(
    col.names = c("Album", "Average danceability"),
    digits = 3,
    booktabs = TRUE,
    linesep = ""
  )
```



\newpage

\appendix

# Appendix {-}




\newpage


# References